CREATE OR REPLACE VIEW DEMO.LANDING.TRANSFORM_DIM_CUSTOMER AS
SELECT CUST.C_CUSTKEY                      AS CUSTOMER_SK
      ,CUST.C_NAME                         AS CUSTOMER_NAME
      ,CUST.C_ADDRESS                      AS CUSTOMER_ADDRESS
      ,CUST.C_PHONE                        AS CUSTOMER_PHONE_NUMBER
      ,CUST.C_MKTSEGMENT                   AS CUSTOMER_MARKET_SEGMENT
      ,NAT.N_NAME                          AS CUSTOMER_NATION
      ,REG.R_NAME                          AS CUSTOMER_REGION
      ,current_timestamp                   AS MERGETIMESTAMP
  FROM DEMO.LANDING.CDC_CUSTOMER           AS CUST
  LEFT JOIN DEMO.LANDING.CDC_NATION        AS NAT  ON CUST.C_NATIONKEY = NAT.N_NATIONKEY
  LEFT JOIN DEMO.LANDING.CDC_REGION       AS REG  ON NAT.N_REGIONKEY = REG.R_REGIONKEY;

CREATE OR REPLACE VIEW DEMO.LANDING.TRANSFORM_DIM_SUPPLIER AS 
SELECT DISTINCT SUP.S_SUPPKEY              AS SUPPLIER_SK,
       SUP.S_NAME                          AS SUPPLIER_NAME,
       SUP.S_ADDRESS                       AS SUPPLIER_ADDRESS,
       SUP.S_PHONE                         AS SUPPLIER_PHONE_NUMBER,
       SUP.METADATA$ACTION                 AS ACTION,
       SUP.METADATA$ISUPDATE               AS ISUPDATE,
       current_timestamp                   AS MERGETIMESTAMP
  FROM DEMO.LANDING.CDC_SUPPLIER           AS SUP 
  LEFT JOIN DEMO.LANDING.CDC_NATION        AS NAT  ON SUP.S_NATIONKEY = NAT.N_NATIONKEY
  LEFT JOIN DEMO.LANDING.CDC_REGION        AS REG  ON NAT.N_REGIONKEY = REG.R_REGIONKEY;


  SELECT TOP 100 *
    FROM DEMO.LANDING.SUPPLIER;

CREATE OR REPLACE VIEW DEMO.LANDING.TRANSFORM_DIM_PART AS 
SELECT COALESCE(PART.P_PARTKEY, PSUB.PS_PARTKEY)  AS PART_SK,
       PART.P_NAME                                AS PART_NAME,
       PART.P_MFGR                                AS PART_MANUFACTUROR,
       PART.P_BRAND                               AS PART_BRAND,
       PART.P_TYPE                                AS PART_TYPE,
       PART.P_SIZE                                AS PART_SIZE,
       PART.P_CONTAINER                           AS PART_CONTAINER,
       PART.METADATA$ACTION                       AS ACTION,
       PART.METADATA$ISUPDATE                     AS ISUPDATE,
       current_timestamp                          AS MERGETIMESTAMP
  FROM DEMO.LANDING.CDC_PART                      AS PART 
  LEFT JOIN DEMO.LANDING.CDC_PARTSUPP             AS PSUB  ON PART.P_PARTKEY = PSUB.PS_PARTKEY;

CREATE OR REPLACE TABLE DEMO.CONFORMED.DIM_SUPPLIER 
(
SUPPLIER_PK INT IDENTITY NOT NULL,
SUPPLIER_SK NUMBER(38,0) NOT NULL COMMENT 'JOIN',
SUPPLIER_NAME VARCHAR(25) NULL,
SUPPLIER_ADDRESS VARCHAR(40) NULL,
SUPPLIER_PHONE_NUMBER VARCHAR(15) NULL,
MERGETIMESTAMP TIMESTAMP_LTZ(9)
);

CREATE OR REPLACE TABLE DEMO.CONFORMED.DIM_PART
(
PART_PK INT IDENTITY NOT NULL,
PART_SK NUMBER(38,0) NOT NULL COMMENT 'JOIN',
PART_NAME VARCHAR(55) NULL,
PART_MANUFACTUROR VARCHAR(25) NULL,
PART_BRAND VARCHAR(10) NULL,
PART_TYPE VARCHAR(25) NULL,
PART_SIZE NUMBER(38,0) NULL,
PART_CONTAINER VARCHAR(10) NULL,
MERGETIMESTAMP TIMESTAMP_LTZ(9)
);


create or replace view DEMO.LANDING.TRANSFORM_DIM_CUSTOMER AS 
SELECT CUST.C_CUSTKEY                      AS CUSTOMER_SK
      ,CUST.C_NAME                         AS CUSTOMER_NAME
      ,CUST.C_ADDRESS                      AS CUSTOMER_ADDRESS
      ,CUST.C_PHONE                        AS CUSTOMER_PHONE_NUMBER
      ,CUST.C_MKTSEGMENT                   AS CUSTOMER_MARKET_SEGMENT
      ,NAT.N_NAME                          AS CUSTOMER_NATION
      ,REG.R_NAME                          AS CUSTOMER_REGION
      ,CUST.METADATA$ACTION                AS ACTION
      ,CUST.METADATA$ISUPDATE              AS ISUPDATE
      ,current_timestamp                   AS MERGETIMESTAMP
  FROM DEMO.LANDING.CDC_CUSTOMER           AS CUST
  LEFT JOIN DEMO.LANDING.CDC_NATION        AS NAT  ON CUST.C_NATIONKEY = NAT.N_NATIONKEY
  LEFT JOIN DEMO.LANDING.CDC_REGION       AS REG  ON NAT.N_REGIONKEY = REG.R_REGIONKEY;


  SELECT TOP 100 *
    FROM DEMO.CONFORMED.DIM_SUPPLIER;