CREATE OR REPLACE VIEW DEMO.LANDING.CUSTOMER_HASH AS 
SELECT C_CUSTKEY
      ,C_NAME
      ,C_ADDRESS
      ,C_NATIONKEY
      ,C_PHONE
      ,C_ACCTBAL
      ,C_MKTSEGMENT
      ,C_COMMENT
      ,HASH(C_CUSTKEY,C_NAME,C_ADDRESS,C_NATIONKEY,C_PHONE,C_ACCTBAL,C_MKTSEGMENT,C_COMMENT) AS HASH_KEY
  FROM DEMO.LANDING.CUSTOMER;

  SELECT TOP 100 *
    FROM DEMO.LANDING.CUSTOMER_HASH;

    INSERT INTO DEMO.LANDING.CUSTOMER SELECT *
      FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER SAMPLE (5 ROWS);

      ALTER TABLE DEMO.STAGING.CUSTOMER ADD MERGE_TMSP DATETIME;

MERGE INTO DEMO.STAGING.CUSTOMER AS DEST 
USING 
(
SELECT C_CUSTKEY
      ,C_NAME
      ,C_ADDRESS
      ,C_NATIONKEY
      ,C_PHONE
      ,C_ACCTBAL
      ,C_MKTSEGMENT
      ,C_COMMENT
      ,HASH_KEY
  FROM DEMO.LANDING.CUSTOMER_HASH
) AS SOURCE 

ON SOURCE.C_CUSTKEY = DEST.C_CUSTKEY

WHEN MATCHED AND SOURCE.HASH_KEY <> DEST.HASH_KEY
THEN UPDATE SET
DEST.C_CUSTKEY = SOURCE.C_CUSTKEY 
,DEST.C_NAME = SOURCE.C_NAME
,DEST.C_ADDRESS = SOURCE.C_ADDRESS
,DEST.C_NATIONKEY = SOURCE.C_NATIONKEY
,DEST.C_PHONE = SOURCE.C_PHONE
,DEST.C_ACCTBAL = SOURCE.C_ACCTBAL
,DEST.C_MKTSEGMENT = SOURCE.C_MKTSEGMENT
,DEST.C_COMMENT = SOURCE.C_COMMENT
,DEST.HASH_KEY = SOURCE.HASH_KEY
,DEST.MERGE_TMSP = current_timestamp()

WHEN NOT MATCHED BY SOURCE
THEN DELETE

WHEN NOT MATCHED BY DEST
THEN INSERT 
(
C_CUSTKEY
,C_NAME
,C_ADDRESS
,C_NATIONKEY
,C_PHONE
,C_ACCTBAL
,C_MKTSEGMENT
,C_COMMENT
,HASH_KEY
)
VALUES 
(
SOURCE.C_CUSTKEY
,SOURCE.C_NAME
,SOURCE.C_ADDRESS
,SOURCE.C_NATIONKEY
,SOURCE.C_PHONE
,SOURCE.C_ACCTBAL
,SOURCE.C_MKTSEGMENT
,SOURCE.C_COMMENT
,SOURCE.HASH_KEY
);